version: "2"
services:
        nginx:
                build: nginx
                depends_on: [orthanc, liveshare]
                restart: unless-stopped
                ports: ["80:80"]
        orthanc:
                build: orthanc-debian
                restart: unless-stopped
                ports: ["8042:8042"]
                volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]
        liveshare:
                build: liveshare
                restart: unless-stopped
                # environment:
                #         - LIVESHARE_CREATION_HOOK=http://auth_api:5000/hooks/liveshare/sessions
                #         - LIVESHARE_CREATION_HOOK_METHOD=POST
                #         - LIVESHARE_UPDATE_HOOK=http://auth_api:5000/hooks/liveshare/sessions/$${liveshareSessionId}
                #         - LIVESHARE_UPDATE_HOOK_METHOD=PUT
                #         - LIVESHARE_DELETION_HOOK=http://auth_api:5000/hooks/liveshare/sessions/$${liveshareSessionId}
                #         - LIVESHARE_DELETION_HOOK_METHOD=DELETE

volumes:
        orthanc-storage:
