version: "2"
services:
  orthanc:
    image: osimis/orthanc
    ports: ["8042:8042"]
    environment:
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "true"

      # you must enable the StoneViewer and the DicomWeb plugins
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"

      ORTHANC__DICOM_WEB__SERIES_METADATA: "MainDicomTags"
      ORTHANC__DICOM_WEB__STUDIES_METADATA: "MainDicomTags"

      ORTHANC__EXTRA_MAIN_DICOM_TAGS: |
        {
          "Instance" : [
              "Rows",
              "Columns",
              "ImageType",
              "SOPClassUID",
              "ContentDate",
              "ContentTime",
              "FrameOfReferenceUID",
              "PixelSpacing",
              "SpecificCharacterSet",
              "BitsAllocated",
              "BitsStored",

              "RescaleSlope",
              "RescaleIntercept",
              "SliceThickness",
              "WindowCenter",
              "WindowWidth",
              "PhotometricInterpretation",
              "PixelRepresentation"
          ],
          "Series" : [
              "TimezoneOffsetFromUTC",
              "PerformedProcedureStepStartDate",
              "PerformedProcedureStepStartTime",
              "RequestAttributesSequence"
          ],
          "Study": [
              "TimezoneOffsetFromUTC"
          ],
          "Patient": []
          }

      # StoneViewer configurations
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "DD/MM/YYYY"

      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
