version: "3.3"

services:
    orthanc:
        image: osimis/orthanc-pro:new-pro-images
        ports: [8042:8042]
        environment:
            - ORTHANC__AWS_S3_STORAGE__BUCKET_NAME=test-orthanc-s3-plugin
            - ORTHANC__AWS_S3_STORAGE__REGION=eu-central-1
            - ORTHANC__AWS_S3_STORAGE__ACCESS_KEY=AK123456789

            - ORTHANC__POSTGRESQL__HOST=database-test.cluster-cydazert.eu-central-1.rds.amazonaws.com
            - ORTHANC__POSTGRESQL__PORT=5432
            - ORTHANC__POSTGRESQL__USERNAME=postgres
            - ORTHANC__POSTGRESQL__DATABASE=
            - ORTHANC__POSTGRESQL__ENABLE_SSL=true

            - ORTHANC__AUTHENTICATION_ENABLED=false
            - ORTHANC__DICOM_SERVER_ENABLED=false

        secrets:
          - ORTHANC__AWS_S3_STORAGE__SECRET_KEY
          - ORTHANC__POSTGRESQL__PASSWORD

secrets:
  ORTHANC__AWS_S3_STORAGE__SECRET_KEY:
    file: aws-s3-secret-key.txt
  ORTHANC__POSTGRESQL__PASSWORD:
    file: rds-password.txt
