version: "3.4"
services:
  orthanc-a:
    image: osimis/orthanc
    ports: ["8042:8042"]
    volumes: ["./tls:/tls", ]
    environment:
      DICOM_WEB_PLUGIN_ENABLED: "true"
      CONNECTIVITY_CHECKS_PLUGIN_ENABLED: "true"
      ORTHANC_JSON: |
        {
          "Name": "orthanc-a",
          "AuthenticationEnabled": false,
          "HttpsVerifyPeers": false,    // since we use self-signed certificates on server side
          "OrthancPeers" : {
            "orthanc-b" : {
              "Url" : "https://orthanc-b:8042",
              "CertificateFile" : "/tls/client-crt.pem",
              "CertificateKeyFile" : "/tls/client-key.pem",
              "CertificateKeyPassword": "password"
            }
          },
          "DicomWeb" : {
            "Servers": {
              "orthanc-b" : {
                "Url" : "https://orthanc-b:8042/dicom-web",
                "CertificateFile" : "/tls/client-crt.pem",
                "CertificateKeyFile" : "/tls/client-key.pem",
                "CertificateKeyPassword": "password"
              }
            }
          }
        }
  orthanc-b:
    image: osimis/orthanc
    ports: ["8043:8042"]
    volumes: ["./tls:/tls"]
    environment:
      VERBOSE_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC_JSON: |
        {
          "Name": "orthanc-b",
          "AuthenticationEnabled": false,

          "SslEnabled": true,
          "SslCertificate": "/tls/server-crt+key.pem",
          "SslTrustedClientCertificates": "/tls/client-crt.pem",
          "SslVerifyPeers": true
        }
    healthcheck:
      test: ["CMD-SHELL", "/probes/test-aliveness.py --certfile=/tls/client-crt.pem --keyfile=/tls/client-key.pem"]
      start_period: 10s
      retries: 2
      interval: 10s
      timeout: 5s