version: "2"
services:
        orthanc:
                build: orthanc
                restart: unless-stopped
                ports: ["8042:8042"]
                volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]
                environment:
                        - NAME=Orthanc for Serve Folders demo
                        - VERBOSE_ENABLED=true
                        - AC_AUTHENTICATION=true
                        - |
                          AC_REGISTERED_USERS=
                          {"demo": "demo"}
volumes:
        orthanc-storage:
