version: "2"
services:
    nginx:
        build: nginx
        depends_on: [orthanc-a, orthanc-b]
        restart: unless-stopped
        ports: ["443:443"]
        volumes: ["nginx-tls:/etc/nginx/tls:Z"]
    orthanc-a:
        image: osimis/orthanc
        restart: unless-stopped
        environment:
            - NAME=Orhtanc A
            - DICOM_AET=ORTHANC-A
            - |
              DICOM_MODALITIES={"orthanc-b": ["ORTHANC-B", "orthanc-b", 4242]}
    orthanc-b:
        image: osimis/orthanc
        restart: unless-stopped
        environment:
            - NAME=Orhtanc B
            - DICOM_AET=ORTHANC-B
volumes:
        nginx-tls:
