version: "2"
services:
  # first setup through configuration file and build step
  orthanc:
    build: orthanc
    depends_on: [orthanc-index]
    restart: unless-stopped
    ports: ["104:4242", "80:8042"]
    volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]

  orthanc-index:
    image: postgres
    restart: unless-stopped
    volumes: ["orthanc-index:/var/lib/postgresql/data:Z"]
    environment:
      ORTHANC__POSTGRESQL__PASSWORD: "postgres"

  # second setup through environment variables
  orthanc-b:
    image: osimis/orthanc
    restart: unless-stopped
    depends_on: [orthanc-index-b]
    ports: ["81:8042"]
    environment:
      ORTHANC__POSTGRESQL__HOST: "orthanc-index-b"
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}

  orthanc-index-b:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-storage:
  orthanc-index:
