version: '3.8'
services:
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - orthanc
      - ohif

  ohif:
    build: ohif
    restart: unless-stopped
    depends_on:
      - orthanc

  orthanc:
    image: osimis/orthanc:23.5.0
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for OHIF"

      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"

      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/ohif/"

      ORTHANC__AUTHENTICATION_ENABLED: "false"

      VERBOSE_STARTUP: "true"

    volumes:
      - orthanc-storage:/var/lib/orthanc/db/
 
volumes:
  orthanc-storage:
