version: "2"
services:
        foo:
                image: osimis/orthanc
                ports: ["80:8042"]
                environment:
                        NAME: Foo
                        DICOM_AET: FOO
                        DICOM_MODALITIES: >
                                {
                                        "bar": ["BAZ", "bar", 4242],
                                        "baz": ["BAR", "baz", 4242]
                                }

        bar:
                image: osimis/orthanc
                ports: ["81:8042"]
                environment:
                        NAME: Bar
                        DICOM_AET: BAR
        baz:
                image: osimis/orthanc
                ports: ["82:8042"]
                environment:
                        NAME: Baz
                        DICOM_AET: BAZ
