version: "2"
services:
        nginx:
                build: nginx
                depends_on: [orthanc, liveshare]
                restart: unless-stopped
                ports: ["80:80"]
        orthanc:
                image: osimis/orthanc-pro
                restart: unless-stopped
                volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]
                environment:
                        - WVP_ALPHA_ENABLED=true
                        - WVP_LIVESHARE_ENABLED=true
                        # note: this is a trial license expiring on 2019-01-15, replace with your license code
                        # Prefer using Docker secret instead of environment variable whenever possible
                        - WVP_LICENSE_STRING=1a6aau3gTMKG6K3Nx%k___demo-orthanc%example.com___aaabu5Ka4njdeAfZZpkSjLrfF7qArwUic7THDYCJwqthrqS
                        - WVP_ANNOTATIONS_STORAGE_ENABLED=true
        liveshare:
                build: liveshare
                restart: unless-stopped
                # environment:
                #         - LIVESHARE_CREATION_HOOK=http://auth_api:5000/hooks/liveshare/sessions
                #         - LIVESHARE_CREATION_HOOK_METHOD=POST
                #         - LIVESHARE_UPDATE_HOOK=http://auth_api:5000/hooks/liveshare/sessions/$${liveshareSessionId}
                #         - LIVESHARE_UPDATE_HOOK_METHOD=PUT
                #         - LIVESHARE_DELETION_HOOK=http://auth_api:5000/hooks/liveshare/sessions/$${liveshareSessionId}
                #         - LIVESHARE_DELETION_HOOK_METHOD=DELETE

volumes:
        orthanc-storage:
