version: "2"
services:
        orthanc:
                image: osimis/orthanc-pro:am-update-mssql
                depends_on: [index]
                ports: ["104:4242", "80:8042"]
                volumes: ["storage:/var/lib/orthanc/db:Z"]
                environment:
                        # note: this is a trial license expiring on 2020-03-15, replace with your license code
                        # Prefer using Docker secret instead of environment variable whenever possible
                        - MSSQL_LICENSE_STRING=1amaaxUUDEKYdYnLda0___demo%osimis.io___aaabLT7F6FMHuef4JeJ6NLaqu4MVbvuJrnmgWksJvjc5VAB4
                        - MSSQL_CONNECTION_STRING=Driver={ODBC Driver 13 for SQL Server};Server=tcp:index,1433;Database=master;Uid=sa;Pwd=MyStrOngPa55word!;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;
                        - MSSQL_MAXIMUM_CONNECTION_RETRIES=4
                        - MSSQL_CONNECTION_RETRY_INTERVAL=8
                        - |
                          AC_REGISTERED_USERS=
                          {"demo": "demo"}
                restart: unless-stopped
        index:
                image: microsoft/mssql-server-linux
                volumes: ["index:/var/opt/mssql/data:Z"]
                environment:
                        - ACCEPT_EULA=Y
                        - SA_PASSWORD=MyStrOngPa55word!

                restart: unless-stopped
volumes:
        storage:
        index:
