version: "2"
services:
  orthanc-new-mssql:
    image: orthancteam/orthanc
    depends_on: [new-index]
    ports: ["8042:8042"]
    volumes: ["storage:/var/lib/orthanc/db"]
    environment:
      ORTHANC__ODBC__INDEX_CONNECTION_STRING: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:new-index,1433;Database=orthanctest;Uid=sa;Pwd=MyStrOngPa55word!;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"
      ORTHANC__ODBC__ENABLE_INDEX: "true"
      ORTHANC__ODBC__ENABLE_STORAGE: "false"
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "true"
    restart: unless-stopped
  new-index:
    build: index
    ports: ["1434:1433"]
    volumes: ["index:/var/opt/mssql"]
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrOngPa55word!"
    restart: unless-stopped


volumes:
  storage:
  index:
