version: "2"
services:
        orthanc-a:
                image: osimis/orthanc
                ports: ["104:4242", "80:8042"]
                environment:
                        # this is one way to specify the environment variables
                        AC_AUTHENTICATION_ENABLED: "true"
                        AC_REGISTERED_USERS: |
                          {"demo": "demo"}
                        NAME: "Orthanc A"
                        DICOM_AET: "ORTHANCA"
                        DICOM_MODALITIES: |
                          {
                             "b": ["ORTHANCB", "orthanc-b", 4242]
                          }

        orthanc-b:
                image: osimis/orthanc
                ports: ["105:4242", "81:8042"]
                environment:
                        # this is another way to specify the environment variables
                        - AC_AUTHENTICATION=true
                        - |
                          AC_REGISTERED_USERS=
                          {"demo": "demo"}
                        - NAME=Orthanc B
                        - DICOM_AET=ORTHANCB
                        - |
                          DICOM_MODALITIES=
                          {
                             "a": ["ORTHANCA", "orthanc-a", 4242]
                          }
