version: "2"
services:
  orthanc-a:
    image: orthancteam/orthanc:24.4.0
    ports: ["104:4242", "80:8042"]
    volumes: ["storage-a:/var/lib/orthanc/db/"]
    environment:
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
      ORTHANC__NAME: "Orthanc A"
      ORTHANC__DICOM_AET: "ORTHANCA"
      ORTHANC__DICOM_MODALITIES: |
        {
          "b": ["ORTHANCB", "orthanc-b", 4242]
        }

  orthanc-b:
    image: orthancteam/:24.4.0
    ports: ["105:4242", "81:8042"]
    volumes: ["storage-b:/var/lib/orthanc/db/"]
    environment:
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
      ORTHANC__NAME: "Orthanc B"
      ORTHANC__DICOM_AET: "ORTHANCB"
      ORTHANC__DICOM_MODALITIES: |
        {
          "a": ["ORTHANCA", "orthanc-a", 4242]
        }
volumes:
  storage-a:
  storage-b:
