version: "2"
services:
        orthanc:
                image: osimis/orthanc
                ports: ["80:8042"]
                environment:
                - AC_AUTHENTICATION_ENABLED=true
                - |
                  AC_REGISTERED_USERS=
                  {
                    "foo": "baz"
                  }
