version: "2"
services:
        orthanc-storage:
                image: osimis/orthanc
                depends_on: [index]
                ports: ["104:4242", "80:8042"]
                volumes: ["storage:/var/lib/orthanc/db:Z"]
                environment:
                        PG_HOST: index
                restart: unless-stopped

        orthanc-viewer:
                image: osimis/orthanc
                depends_on: [index]
                ports: ["105:4242", "81:8042"]
                volumes: ["storage:/var/lib/orthanc/db:Z"]
                environment:
                        - PG_HOST=index
                        - WVB_ENABLED=true
                restart: unless-stopped

        index:
                image: postgres
                volumes: ["index:/var/lib/postgresql/data:Z"]
                restart: unless-stopped
volumes:
        storage:
        index:
