version: "2"
services:
        foo:
                image: osimis/orthanc
                ports: ["104:4242", "80:8042"]
                environment:
                        NAME: Foo
                        PEERING_PEERS: |
                                {
                                        "bar": ["http://bar:8042/"]
                                }
        bar:
                image: osimis/orthanc
                ports: ["105:4242", "81:8042"]
                environment:
                        NAME: Bar
                        PEERING_PEERS: |
                                {
                                        "foo": ["http://foo:8042/"]
                                }
