version: "3"
services:

  nginx:
    build: nginx
    depends_on: [orthanc-for-admin, orthanc-for-users, pacs]
    restart: unless-stopped
    ports: ["80:80"]


  # first setup through configuration file and build step
  orthanc-for-admin:
    build: orthanc
    volumes: ["orthanc-storage:/var/lib/orthanc/db"]
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for admin"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__REGISTERED_USERS: |
        {"admin": "admin"}
      ORTHANC__OVERWRITE_INSTANCES: "true"

    env_file:
      - common-orthanc.env

  orthanc-for-users:
    build: orthanc
    volumes: ["orthanc-storage:/var/lib/orthanc/db"]
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for users"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_UPLOAD: "false"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_DICOM_MODALITIES: "false"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_DELETE_RESOURCES: "false"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_SETTINGS: "false"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_LINK_TO_LEGACY_UI: "false"
      ORTHANC__REGISTERED_USERS: |
        {"user": "user"}
      ORTHANC__OVERWRITE_INSTANCES: "true"

    env_file:
      - common-orthanc.env

  orthanc-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


  pacs:
    image: orthancteam/orthanc
    volumes: ["pacs-storage:/var/lib/orthanc/db"]
    depends_on: [pacs-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Pacs"
      ORTHANC__DICOM_AET: "PACS"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__POSTGRESQL__HOST: "pacs-db"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_MODALITIES: |
        {"orthanc": ["ORTHANC", "orthanc-for-admin", 4242]}

  pacs-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["pacs-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-storage:
  orthanc-db:
  pacs-storage:
  pacs-db:
